### ISSUE TITLE
htmlChecker

### ISSUE THREAD

**Issue by frkcn** [19ceng/ceng203vy#12]
#### soru:

```
<html>
    <title>ceng203vy</title>
    <body>
        <h1>Mufredat</h1>
        bu <b>koyu</b> bu <i>italik</i> bu ise <b><i>italik</i>koyu</b>
    </body>
</html>
```

Örneğin böyle bir html dosyasını check edebilecek bir program:

`def: htmlchecker`

**sonuçta:** `tags = ['html', 'title', '/title', 'body', '/body', 'h1', '/h1', '/body', '/html']`

Bu **dengeli mi dengesiz mi** tasarla.
##### çıktı:
- 1- `dengeli`
- 2- `dengesiz`

**Comment by seyyah** [comment]
örnek çalışma

```
>>> tags = ['html', 'title', '/title', 'body', '/body', 'h1', '/h1', '/body', '/html']
>>> htmlChecker(tags)
dengeli
```

**Comment by frkcn** [comment]
#### bir çözüm:

https://gist.github.com/720440
