### ISSUE TITLE
htmlChecker: regular expression

### ISSUE THREAD

**Issue by frkcn** [19ceng/ceng203vy#13]
#### soru:

Çalışma sorusu 6'yı **expression** alacak şekilde düzenleyin.
`index.html` i alsın ve **dengeli mi dengesiz mi** söylesin.

**İpucu:** `< >` önce `<` sembole rastlasın ve içindekileri almaya başlasın `>` işareti görünce bitirsin. (En ilkel hali)

**Profesyonel halini `regexp` ile yapabiliriz.**
##### çıktı:
- `dengeli`
- `dengesiz`

**Comment by seyyah** [comment]
python ile regular expression (düzenli ifade) kılavuzları,
- http://docs.python.org/library/re.html
- http://diveintopython.org/regular_expressions/index.html

**Comment by seyyah** [comment]
ör. kabukta neler oluyor?

```
>>> import re
>>> str = "<html>foo </html>bar"
>>> re.findall(r'<[/]*\w+>', str)
['<html>', '</html>']
```

**Comment by emineker** [comment]
hocam bu örnek örneğin <style font=2 ...> şeklindekileri almıyo ama kapanışını alıyo ( </style> )

**Comment by seyyah** [comment]
@emineker doğrudur ben burada ipucunu ve devamındakileri nerede bulacağınızı gösterdim (bk. ilgili [yorum](http://github.com/19ceng/ceng203vy/issues#issue/13/comment/495796)).

bahsettiğin örnek için de geçerli olacak şekilde düzenli ifade,

```
>>> str = '<html>foo <style foo=bar></html>bar'
>>> re.findall(r'<[/]*\w+[^>]*>', str)
['<html>', '<style foo=bar>', '</html>']
>>> 
```

hala yapmak gereken işçilik var;)

**Comment by seyyah** [comment]
RE ipuçları
- `[/]*` slaş karakteri `0` veya daha fazla kez çıksın (@nurettins: 0-1 olacak şekilde düzelt)
- `\w+` alphanumerik karakter `1` veya daha fazla olacak
- `[^>]*` `>` dışındaki herhangi bir karakter (boşluk dahil) `0` veya daha fazla çıksın

**özet:** dolayısıyla `<` ile başlayan `/` olabilir olmayabilir, `alfakarekter` gelsin sonrasında `attribute` olabilir de olmayabilir de en sonunda `>` olsun.

**Comment by emineker** [comment]
http://github.com/emineker/python/blob/master/modul/re.py

**Comment by seyyah** [comment]
kritik işlevler: `parser`, `htmlChecker`. dosya kabul eder, `parser("index.html")` tags leri içeren liste döndürür.

**Comment by seyyah** [comment]
`htmlChecker` ın `True`/`False` döndüren versiyonu ve bilgi/hata mesajı döndüren versiyonu [src](https://github.com/19ceng/ceng203vy/tree/master/src/) dizini altına konuldu. Şunlara özel dikkat ediniz,
1. `parser` işlevinin görevi nedir? Girdi ve çıktısı nedir?
2. `Stack` kullanmaksızın `list` ile çözebilir miyiz? Veya ne gibi durumları yakalayamayız?
3. `matches` işlevinde `close` yerine `close[1:]` kullanılmış neden?
4. her bir test dosyası `index1-4.htm` farklı özellikleri sahip
5. buradaki gerçekleme `<font color=red>bla bla</font>` benzeri bir yapıdaki eşleşmeyi yakalayabilir mi?

**Comment by seyyah** [comment]
`checker` işlevi `parChecker` daki dengeli parantezle çok benzerdir. `while` döngüsünde `balanced` değişkeninin kaldırılmasının nedeni ne olabilir?
