### ISSUE TITLE
Hanoi oyunu

### ISSUE THREAD

**Issue by frkcn** [19ceng/ceng203vy#21]
#### soru:
- **Hanoi** oyununu otomatik oynayacak.
- `N` tane **disk** seçilecek.
- başlangıç kule = sol
- hedef kule = sağ
- **Kural 1:** Bir anda bir tane disk hareket etmeli.
- **Kural 2:** Büyük diskler her zaman altta olmalı.
- ![baslangıç](https://github.com/frkcn/image/raw/master/baslangic.jpg) ![tampon](https://github.com/frkcn/image/raw/master/tampon.jpg)  ![hedef](https://github.com/frkcn/image/raw/master/baslangic.jpg)
-   başlangıç  ----  tampon  ---- hedef
#### Kullanım

```
    >>> hanoi_kulesi(3)
    Aşama 0: 
                Sol   : 3 2 1
                Orta  : 
                Sağ   :  
    Aşama 1:    
                Sol   : 3 2  
                Orta  : 
                Sağ   : 1

    Aşama 2:    
                Sol   : 3
                Orta  : 2
                Sağ   : 1

    Aşama 3:    
                Sol   : 3
                Orta  : 2 1
                Sağ   : 

    Aşama 4:    
                Sol   : 
                Orta  : 2 1
                Sağ   : 3

    Aşama 5:    
                Sol   : 1
                Orta  : 2
                Sağ   : 3

    Aşama 6:    
                Sol   : 1
                Orta  : 
                Sağ   : 3 2

    Aşama 7:    
                Sol   : 
                Orta  : 
                Sağ   : 3 2 1
```

**Comment by seyyah** [comment]
[wikipedia](http://en.wikipedia.org/wiki/Tower_of_Hanoi#Iterative_solution) daki çözüm yaklaşımı şöyle verilmiş:

> For an even number of disks:
> 
> ```
> * make the legal move between pegs A and B
> * make the legal move between pegs A and C
> * make the legal move between pegs B and C
> * repeat until complete
> ```
> 
> For an odd number of disks:
> 
> ```
> * make the legal move between pegs A and C
> * make the legal move between pegs A and B
> * make the legal move between pegs B and C
> * repeat until complete
> ```
> 
> In each case, a total of 2n-1 moves are made.

burada `A - B - C` kuleleri temsil eder.

**Comment by seyyah** [comment]
yığıt için depoya eklenen güncel [Stack](https://github.com/19ceng/ceng203vy/blob/master/src/stack.py) gerçeklemesini kullanabilirsiniz.

burada yeni olan nedir?
- yığıt boşken `peek` ve `pop` artık `None` döndürüyor
- yeni yöntem eklendi-`show` bununla yığıt içeriğini gösterebiliriz

**Comment by seyyah** [comment]
algoritmada bahsedilen _legal_ hareket işlevi nasıl olmalıdır. öncelikle arayüzü şöyle olabilir

```
 def move(X, Y):
```

yani `X` kulesi ile `Y` kulesi arasında disk taşıması yapılacak. bu işlev tasarlanırken şu durumları dikkate alınız
- `X` yığıtı boşsa (=`None`) ne anlama gelir? taşıma nereden nereye olabilir?
- benzer şekilde `Y` yığıtı boşsa ne anlama gelir? taşıma nereden nereye olabilir?
- her ikisi boşsa ne anlama gelir?
- her iki yığıtta bir şeyler varsa, _legal_ hareket yönünü nasıl belirleriz?

**Comment by seyyah** [comment]
taşıma işinin bitmesini en kolay şöyle sınayabiliriz

```
 def bitti_mi(C, n):
            return C.size() == n
```

burada `C` hedef kule yığıtı, `n` disk sayısıdır. eğer hedef kulede `n` adet değer varsa tüm diskler taşınmış demektir.

**Comment by seyyah** [comment]
çözüm burada: https://gist.github.com/672604
