### ISSUE TITLE
Çiçek fraktal

### ISSUE THREAD

**Issue by nuryslyrt** [19ceng/ceng203vy#49]
http://www.flickr.com/photos/60427550@N08/6606500447/  
 verildiği biçimde olan fraktal çizen özyineli
çiçek(x,y,r,h) işlevi tasarlanmak istenmektedir. Bu
amaçla çember(x,y,r) yardımcı işlevini kullanabilirsiniz.
Burada (x,y) merkez, r: yarıçap ve h: derinliktir.
Yandaki gösterimde h=3, (x,y) = (0,0) seçilmiştir. En
büyük yarıçaplı (beyaz) çember “r” yarı çapındayken, orta
boy olan “r/2” ve en küçük olan da “r/4” yarı çapındadır.

**Comment by nuryslyrt** [comment]
@seyyah  hocam bu konuda bize yardımcı olur musunuz acaba ?

**Comment by seyyah** [comment]
@1zinnur9 hangi çember (üst-alt-sağ-sol ve büyük) hangi sırayla çiziliyor. Onu belirlerseniz gerisi 5 satırlık kod

**Comment by nuryslyrt** [comment]
@seyyah  hocam kusura bakmayın hemen bir şeyler deneyemedim ama şunu yaptım. Oldu mu acaba : https://gist.github.com/1547552 => kodlarım.
Ekran çıktım : http://www.flickr.com/photos/60427550@N08/6612705923/
Renkleri biraz değiştirdim ama... :-)
