### ISSUE TITLE
StackN SVT

### ISSUE THREAD

**Issue by frkcn** [19ceng/ceng203vy#7]
#### soru:

Yığıtımızı `n` değeri ile sınırlayacak olursak bunun üzerine eleman eklediğimizde **yığıt dolu** şeklinde hata raporu verecek bir program yazınız.

**Not:** Listing `2.2` de ki `def pop` kısmını iyileştir.
##### çıktı:
- `>>> Yığıt dolu`

**Comment by seyyah** [comment]
burada tasarlanacak SVT ismi `Stack(N)` olacak ve şöyle bir arayüzü olacak,

```
>>> s = StackN(10)
>>> 
```
